---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: manager-role
  namespace: openshift-catalogd
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
