---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: catalogd-manager-role
rules:
  - apiGroups:
      - catalogd.operatorframework.io
    resources:
      - clustercatalogs
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - catalogd.operatorframework.io
    resources:
      - clustercatalogs/finalizers
    verbs:
      - update
  - apiGroups:
      - catalogd.operatorframework.io
    resources:
      - clustercatalogs/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - pods/log
    verbs:
      - get
      - list
      - watch
