---
apiVersion: v1
kind: Service
metadata:
  name: catalogd-webhook-service
  namespace: openshift-catalogd
spec:
  ports:
    - port: 443
      targetPort: 9443
  selector:
    control-plane: catalogd-controller-manager
